### ISSUE TITLE
Cannot invoke Remote Function from Server

### ISSUE THREAD

**Issue by mandrillxx** [Sleitnick/rbxts-proton#6]
Hi, I am not sure if this was intentional or not, but here is the Typings for NetFunctionServer and NetFunctionClient.

```
declare class NetFunctionServer<TX extends unknown[] | unknown, RX extends unknown[] | unknown> {
    private readonly rf;
    constructor(rf: RemoteFunction);
    /**
     * Handle invocations to this remote function coming from clients.
     * @param handler Handler
     */
    handle(handler: (player: Player, ...args: NetworkParams<TX>) => NetworkReturn<RX>): void;
}
declare class NetFunctionClient<TX extends unknown[] | unknown, RX extends unknown[] | unknown> {
    private readonly rf;
    constructor(rf: RemoteFunction);
    /**
     * Invoke the remote function, sending the arguments to the server.
     * @param args TX
     * @returns RX
     */
    invoke(...args: NetworkParams<TX>): Promise<NetworkReturn<RX>>;
}
```

Their is no invokeClient as there should be per https://create.roblox.com/docs/reference/engine/classes/RemoteFunction#InvokeClient

Is there a reason behind this?

**Comment by Sleitnick** [comment]
It can be dangerous to invoke a client function from the server. There's no guarantee as to what the client function will do. To prevent bad practice, the ability to invoke client functions was intentionally left out of Proton. Roblox has a note about this in their documentation [here](https://create.roblox.com/docs/scripting/events/remote-events-and-functions#server-to-client-to-server).
